export const specialDomains = [
  'www.reddit.com',
  'www.dr.dk',
  'tv2.dk',
  'ekstrabladet.dk',
  'politiken.dk',
  'www.bt.dk',
  'jp.dk',
  'jyllands-posten.dk',
  'www.berlingske.dk',
  'msn.dk',
  'www.msn.com',
  'finans.dk',
  //   'jubii.dk',
  'www.dagens.dk',
  'www.dagens.com',
  'www.seoghoer.dk',
  'www.lokalavisen.dk',
  'dinavis.dk',
  'www.nytimes.com',
  'people.com',
  //   'bbc.co.uk',
  ///////////////////////////update2
  //   'bbc.com',
  //   'foxnews.com',
  //   'cnn.com',
  //   'news.google.com',
  //   'yahoo.com',
  //   'theguardian.com',
  //   'dailymail.co.uk',
];
