export const specialDomains = [
  'www.reddit.com',
  'www.dr.dk',
  'tv2.dk',
  'ekstrabladet.dk',
  'politiken.dk',
  'www.bt.dk',
  'jp.dk',
  'jyllands-posten.dk',
  'www.berlingske.dk',
  'msn.dk',
  'www.msn.com',
  //   'Finans.dk',
  //   'jubii.dk',
  //   'dagens.dk',
  //   ////////////////////////////////update1
  //   'seoghoer.dk',
  //   'lokalavisen.dk',
  //   'nytimes.com',
  //   'people.com',
  //   'bbc.co.uk',
  ///////////////////////////update2
  //   'bbc.com',
  //   'foxnews.com',
  //   'cnn.com',
  //   'news.google.com',
  //   'yahoo.com',
  //   'theguardian.com',
  //   'msn.com',
  //   'dailymail.co.uk',
];
