name: Test Artifact Upload 123

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create test file
        run: |
          echo "This is a test file" > test.txt
          mkdir -p output
          mv test.txt output/

      - name: Archive test file
        run: |
          cd output
          zip test.zip test.txt
          cd ..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: output/test.zip
